# encoding: utf-8
"""
This script is based on ColorSplasher by BIMOne. 
All original code from BIMOne is licensed under MIT License, however all modifications and improvements are licensed under a different license agreement included below:

################################

MIT License
Copyright (c) 2021 BIM One Inc.
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

################################

Nonica - License Agreement
For the use of this script
This License Agreement (this “Agreement” of this “License Agreement”) is made and effective as of the current date (the “Commencement Date”) by and between Nonica by Estudio Alonso Candau SLP a company organized and existing in Spain with a registered address at Avd.Chafarinas 16 Puerto Rey Vera, Almeria (“Licensor”) and yourself (“Licensee”).
WHEREAS:
1.	Licensee wishes to obtain access and use this script (hereinafter, the “Asset”), and
2.	Licensor is willing to grant to the Licensee a non-exclusive, non-transferable License to use the Asset for the term and specific purpose set forth in this Agreement,
NOW, THEREFORE, your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use this script.
1. Definitions
1.1 “Agreement” means this License Agreement including the attached Schedule.
1.2 “Confidential Information” means information that:
a. is by its nature confidential;
b. is designated in writing by Licensor as confidential;
c. the Licensee knows or reasonably ought to know is confidential;
d. Information comprised in or relating to any Intellectual Property Rights of Licensor.
1.3 “Asset” means the Asset provided by Licensor as specified in Item 6 of the Schedule in the form as stated in Item 7 of the Schedule.
1.4 “Intellectual Property Rights” means all rights in and to any copyright, trademark, trading name, design, patent, know how (trade secrets) and all other rights resulting from intellectual activity in the industrial, scientific, literary or artistic field and any application or right to apply for registration of any of these rights and any right to protect or enforce any of these rights, as further specified in clause 5.
1.5 “Party” means a person or business entity who has executed this Agreement; details of the Parties are specified in Item 2 of the Schedule.
1.6 “Term” means the term of this Agreement commencing on the Commencement Date as specified in Item 4 of the Schedule and expiring on the Expiry Date specified in Item 5 of the Schedule.
2. License Grant
2.1 Licensor grants to the Licensee a non-exclusive, non-transferable License for the Term to use the Asset for the specific purpose specified in this Agreement, subject to the terms and conditions set out in this Agreement.
3. Charges
3.1 In consideration of the Licensor providing the License under clause 2 of this License Agreement, the Licensee agrees to pay Licensor the amount of the License Charge as specified in Item 9 of the Schedule.
4. Licensee's Obligations
4.1 The Licensee cannot use the Asset, for purposes other than as specified in this Agreement and in Item 8 of the Schedule.
4.2 The Licensee may permit its employees to use the Asset for the purposes described in Item 8, provided that the Licensee takes all necessary steps and imposes the necessary conditions to ensure that all employees using the Asset do not commercialise or disclose the contents of it to any third person, or use it other than in accordance with the terms of this Agreement.
4.3 The Licensee will not distribute, sell, License or sub-License, let, trade or expose for sale the Asset to a third party.
4.4 No copies of the Asset are to be made other than as expressly approved by Licensor.
4.5 No changes to the Asset or its content may be made by Licensee.
4.6 The Licensee will provide technological and security measures to ensure that the Asset which the Licensee is responsible for is physically and electronically secure from unauthorised use or access.
4.7 Licensee shall ensure that the Asset retains all Licensor copyright notices and other proprietary legends and all trademarks or service marks of Licensor.
5. Intellectual Property Rights
5.1 All Intellectual Property Rights over and in respect of the Asset are owned by Licensor. The Licensee does not acquire any rights of ownership in the Asset.
6. Limitation of Liability
6.1 The Licensee acknowledges and agrees that neither Licensor nor its board members, officers, employees or agents, will be liable for any loss or damage arising out of or resulting from Licensor's provision of the Asset under this Agreement, or any use of the Asset by the Licensee or its employees; and Licensee hereby releases Licensor to the fullest extent from any such liability, loss, damage or claim.
7. Confidentiality
7.1 Neither Party may use, disclose or make available to any third party the other Party's Confidential Information, unless such use or disclosure is done in accordance with the terms of this Agreement.
7.2 Each Party must hold the other Party's Confidential Information secure and in confidence, except to the extent that such Confidential Information:
a. is required to be disclosed according to the requirements of any law, judicial or legislative body or government agency; or
b. was approved for release in writing by the other Party, but only to the extent of and subject to such conditions as may be imposed in such written authorisation.
7.3 This clause 7 will survive termination of this Agreement.
8. Disclaimers & Release
8.1 To the extent permitted by law, Licensor will in no way be liable to the Licensee or any third party for any loss or damage, however caused (including through negligence) which may be directly or indirectly suffered in connection with any use of the Asset.
8.2 The Asset is provided by Licensor on an “as is” basis.
8.3 Licensor will not be held liable by the Licensee in any way, for any loss, damage or injury suffered by the Licensee or by any other person related to any use of the Asset or any part thereof.
8.4 Notwithstanding anything contained in this Agreement, in no event shall Licensor be liable for any claims, damages or loss which may arise from the modification, combination, operation or use of the Asset with Licensee computer programs.
8.5 Licensor does not warrant that the Asset will function in any environment.
8.6 The Licensee acknowledges that: a. The Asset has not been prepared to meet any specific requirements of any party, including any requirements of Licensee; and b. it is therefore the responsibility of the Licensee to ensure that the Asset meets its own individual requirements.
8.7 To the extent permitted by law, no express or implied warranty, term, condition or undertaking is given or assumed by Licensor, including any implied warranty of merchantability or fitness for a particular purpose.
9. Indemnification
9.1 The Licensee must indemnify, defend and hold harmless Licensor, its board members, officers, employees and agents from and against any and all claims (including third party claims), demands, actions, suits, expenses (including attorney's fees) and damages (including indirect or consequential loss) resulting in any way from:
a. Licensee's and Licensee's employee's use or reliance on the Asset,
b. any breach of the terms of this License Agreement by the Licensee or any Licensee employee, and
c. any other act of Licensee.
9.2 This clause 9 will survive termination of this Agreement.
10. Waiver
10.1 Any failure or delay by either Party to exercise any right, power or privilege hereunder or to insist upon observance or performance by the other of the provisions of this License Agreement shall not operate or be construed as a waiver thereof.
11. Governing Law
11.1 This Agreement will be construed by and governed in accordance with the laws of Spain. The Parties submit to exclusive jurisdiction of the courts of Spain.
12. Termination
12.1 This Agreement and the License granted herein commences upon the Commencement Date and is granted for the Term, unless otherwise terminated by Licensor in the event of any of the following:
a. if the Licensee is in breach of any term of this License Agreement and has not corrected such breach to Licensor's reasonable satisfaction within 7 days of Licensor's notice of the same;
b. if the Licensee becomes insolvent, or institutes (or there is instituted against it) proceedings in bankruptcy, insolvency, reorganization or dissolution, or makes an assignment for the benefit of creditors; or
c. the Licensee is in breach of clause 5 or 7 of this Agreement.
12.2 Termination under this clause shall not affect any other rights or remedies Licensor may have.
14. Assignment
14.1 Licensee shall not assign any rights of this License Agreement, without the prior written consent of Licensor.
15. Notices
15.1 All notices required under this Agreement shall be in writing and shall be deemed given (i) when delivered personally; (ii) five (5) days after mailing, when sent certified mail, return receipt requested and postage prepaid; or (iii) one (1) business day after dispatch, when sent via a commercial overnight carrier, fees prepaid. All notices given by either Party must be sent to the address of the other as first written above (unless otherwise changed by written notice).
16. Counterparts
16.1 This Agreement may be executed in any number of counterparts, each of which shall be deemed to be an original and all of which taken together shall constitute one instrument.
17. Severability
17.1 The Parties recognize the uncertainty of the law with respect to certain provisions of this Agreement and expressly stipulate that this Agreement will be construed in a manner that renders its provisions valid and enforceable to the maximum extent possible under applicable law. To the extent that any provisions of this Agreement are determined by a court of competent jurisdiction to be invalid or unenforceable, such provisions will be deleted from this Agreement or modified so as to make them enforceable and the validity and enforceability of the remainder of such provisions and of this Agreement will be unaffected.
18. Entire Agreement
18.1 This Agreement contains the entire agreement between the Parties and supersedes any previous understanding, commitments or agreements, oral or written. Further, this Agreement may not be modified, changed, or otherwise altered in any respect except by a written agreement signed by both Parties.
IN WITNESS WHEREOF, this Agreement, including the attached Schedule, was signed by the Parties under the hands of their duly authorized representatives and made effective as of the current date.
Nonica by Estudio Alonso Candau SLP,
Signature
02/05/2021
Jaime Alonso Candau
Please contact hello@nonica.io with any further doubt/request.

################################

Dynamo to pyRevit adaptation by Jean-Marc Couffin, BIMOne inc., 2023/12/11
"""

import os.path
from random import randint
from unicodedata import normalize, category
import clr

clr.AddReference("System")
clr.AddReference("System.Drawing")
clr.AddReference("System.Windows.Forms")
clr.AddReference("System.Data")
import System
from System import String, Enum, Object
from System.Data import DataTable
from System.Drawing import Color, Font, FontStyle, Icon, SolidBrush, Point, Size
from System.Windows.Forms import (
    CheckState,
    ColorDialog,
    ComboBoxStyle,
    DialogResult,
    DrawMode,
    Form,
    FormBorderStyle,
    TextRenderer,
    ComboBox,
    CheckedListBox,
    ListBox,
    Button,
    Label,
    AnchorStyles,
)


from pyrevit import DB, HOST_APP, UI, revit, script
from pyrevit.forms import alert
from pyrevit.framework import List
from re import sub


def solid_fill_pattern_id(new_doc):
    solid_fill_id = None
    fillpatterns = DB.FilteredElementCollector(new_doc).OfClass(
        DB.FillPatternElement
    )
    for pat in fillpatterns:
        if pat.GetFillPattern().IsSolidFill:
            solid_fill_id = pat.Id
            break
    return solid_fill_id


class SubscribeView(UI.IExternalEventHandler):
    def __init__(self):
        self.registered = 1

    def Execute(self, uiapp):
        try:
            if self.registered == 1:
                self.registered = 0
                uiapp.ViewActivated += self.view_changed
            else:
                self.registered = 1
                uiapp.ViewActivated -= self.view_changed
        except Exception:
            pass

    def view_changed(self, sender, e):
        if wndw.IsOpen == 1:
            if self.registered == 0:
                new_doc = e.Document
                if new_doc:
                    new_uiapp = new_doc.Application
                    if wndw:
                        if not new_doc.Equals(doc):
                            wndw.Close()
                # Update categories in dropdown
                new_view = get_active_view(e.Document)
                if new_view != 0:
                    # Unsubcribe
                    wndw._list_box2.SelectedIndexChanged -= (
                        wndw.list_selected_index_changed
                    )
                    # Update categories for new view
                    wndw.crt_view = new_view
                    categ_inf_used_up = get_used_categories_and_parameters(
                        cat_excluded, wndw.crt_view
                    )
                    wndw._categories_table_data = DataTable("Data")
                    wndw._categories_table_data.Columns.Add("Key", String)
                    wndw._categories_table_data.Columns.Add("Value", Object)
                    names = [x._name for x in categ_inf_used_up]
                    wndw._categories_table_data.Rows.Add("Select a Category Here!", 0)
                    [
                        wndw._categories_table_data.Rows.Add(key_, value_)
                        for key_, value_ in zip(names, categ_inf_used_up)
                    ]
                    wndw._categories.DataSource = wndw._categories_table_data
                    wndw._categories.DisplayMember = "Key"
                    # Vaciar range of values
                    wndw._table_data3 = DataTable("Data")
                    wndw._table_data3.Columns.Add("Key", String)
                    wndw._table_data3.Columns.Add("Value", Object)
                    wndw._list_box2.DataSource = wndw._table_data3
                    wndw._list_box2.DisplayMember = "Key"

    def GetName(self):
        return "Subscribe View Changed Event"


class ApplyColors(UI.IExternalEventHandler):
    def __init__(self):
        pass

    def Execute(self, uiapp):
        try:
            new_doc = revit.DOCS.doc
            view = get_active_view(new_doc)
            if view != 0:
                sf = solid_fill_pattern_id(new_doc)
                t = DB.Transaction(new_doc, "Apply colors to elements")
                t.Start()
                sel_cat = wndw._categories.SelectedItem["Value"]
                if (
                    sel_cat._cat.Id.IntegerValue == int(DB.BuiltInCategory.OST_Rooms)
                    or sel_cat._cat.Id.IntegerValue
                    == int(DB.BuiltInCategory.OST_MEPSpaces)
                    or sel_cat._cat.Id.IntegerValue == int(DB.BuiltInCategory.OST_Areas)
                ):
                    # In case of rooms, spaces and areas. Check Color scheme is applied and if not
                    if version > 2021:
                        if (
                            str(wndw.crt_view.GetColorFillSchemeId(sel_cat._cat.Id))
                            == "-1"
                        ):
                            fColorScheme = (
                                DB.FilteredElementCollector(new_doc)
                                .OfClass(DB.ColorFillScheme)
                                .ToElements()
                            )
                            if len(fColorScheme) > 0:
                                for sch in fColorScheme:
                                    if (
                                        sch.CategoryId.IntegerValue
                                        == sel_cat._cat.Id.IntegerValue
                                    ):
                                        if len(sch.GetEntries()) > 0:
                                            wndw.crt_view.SetColorFillSchemeId(
                                                sel_cat._cat.Id, sch.Id
                                            )
                                            break
                    else:
                        wndw._txt_block5.Visible = True
                else:
                    wndw._txt_block5.Visible = False

                for indx in range(wndw._list_box2.Items.Count):
                    ogs = DB.OverrideGraphicSettings().Dispose()
                    ogs = DB.OverrideGraphicSettings()
                    color = DB.Color(
                        wndw._list_box2.Items[indx]["Value"]._n1,
                        wndw._list_box2.Items[indx]["Value"]._n2,
                        wndw._list_box2.Items[indx]["Value"]._n3,
                    )
                    # ogs.SetProjectionLineColor(color)
                    ogs.SetSurfaceForegroundPatternColor(color)
                    ogs.SetCutForegroundPatternColor(color)
                    if sf is not None:
                        ogs.SetSurfaceForegroundPatternId(sf)
                        ogs.SetCutForegroundPatternId(sf)
                    ogs.SetProjectionLinePatternId(DB.ElementId(-1))
                    for id in wndw._list_box2.Items[indx]["Value"]._eleId:
                        view.SetElementOverrides(id, ogs)
                t.Commit()
        except Exception:
            pass

    def GetName(self):
        return "Apply colors to elements"


class ResetColors(UI.IExternalEventHandler):
    def __init__(self):
        pass

    def Execute(self, uiapp):
        try:
            new_doc = revit.DOCS.doc
            view = get_active_view(new_doc)
            if view != 0:
                ogs = DB.OverrideGraphicSettings().Dispose()
                ogs = DB.OverrideGraphicSettings()
                collector = (
                    DB.FilteredElementCollector(new_doc, view.Id)
                    .WhereElementIsNotElementType()
                    .WhereElementIsViewIndependent()
                    .ToElements()
                )
                with revit.Transaction(doc=new_doc, name="Reset colors in elements"):
                    for ele in collector:
                        view.SetElementOverrides(ele.Id, ogs)
        except Exception:
            pass

    def GetName(self):
        return "Reset colors in elements"


class CreateFilters(UI.IExternalEventHandler):
    def __init__(self):
        pass

    def Execute(self, uiapp):
        try:
            new_doc = revit.DOCS.doc
            view = get_active_view(new_doc)
            with revit.Transaction(doc=new_doc, name="Create View Filters"):
                sel_cat = wndw._categories.SelectedItem["Value"]
                sel_par = wndw._list_box1.SelectedItem["Value"]
                categories = List[DB.ElementId]()
                categories.Add(sel_cat._cat.Id)
                sf = solid_fill_pattern_id(new_doc)
                for i, element in enumerate(wndw._list_box2.Items):
                    item = wndw._list_box2.Items[i]["Value"]

                    # Assign color filled region
                    ogs = DB.OverrideGraphicSettings().Dispose()
                    ogs = DB.OverrideGraphicSettings()
                    color = DB.Color(item._n1, item._n2, item._n3)
                    ogs.SetSurfaceForegroundPatternColor(color)
                    ogs.SetCutForegroundPatternColor(color)
                    ogs.SetSurfaceForegroundPatternId(sf)
                    ogs.SetCutForegroundPatternId(sf)

                    # filter naming
                    filter_name = (sel_cat._name + " / " + sel_par._name + " - " + item._value)
                    filter_name = filter_name.strip("{}[]:\|?/<>*")

                    # Create filter
                    parameter_id = DB.ElementId(sel_par._rl_par.Id.IntegerValue)
                    param_storage_type = sel_par._rl_par.StorageType
                    if param_storage_type == DB.StorageType.Double:
                        value = float(sub("[^-\d|.]", "", item._value))
                        if version > 2021:
                            value_to_internal = DB.UnitUtils.ConvertToInternalUnits(
                                value, sel_par._rl_par.GetUnitTypeId()
                            )
                        else:
                            value_to_internal = DB.UnitUtils.ConvertToInternalUnits(
                                value, sel_par._rl_par.DisplayUnitType
                            )
                        equals_rule = DB.ParameterFilterRuleFactory.CreateEqualsRule(
                            parameter_id, value_to_internal, 0.5
                        )
                    elif param_storage_type == DB.StorageType.ElementId:
                        equals_rule = DB.ParameterFilterRuleFactory.CreateEqualsRule(
                            parameter_id, item._value
                        )
                    elif param_storage_type == DB.StorageType.Integer:
                        value = int(sub("[^0-9]", "", item._value))
                        equals_rule = DB.ParameterFilterRuleFactory.CreateEqualsRule(
                            parameter_id, value
                        )
                    elif param_storage_type == DB.StorageType.String:
                        try:
                            equals_rule = (
                                DB.ParameterFilterRuleFactory.CreateEqualsRule(
                                    parameter_id, item._value
                                )
                            )
                        except TypeError:  # different method in versions earlier than R2023
                            equals_rule = (
                                DB.ParameterFilterRuleFactory.CreateEqualsRule(
                                    parameter_id, item._value, True
                                )
                            )
                    else:
                        alert(msg="Filter Creation for this Parameter type is not supported: {}".format(sel_par._rl_par.StorageType), title="Error")
                        break
                    elem_filter = DB.ElementParameterFilter(equals_rule)
                    fltr = DB.ParameterFilterElement.Create(
                        new_doc, filter_name, categories, elem_filter
                    )
                    view.AddFilter(fltr.Id)
                    view.SetFilterOverrides(fltr.Id, ogs)
        except Exception as e:
            alert(msg="{}\nFilter Creation for this Parameter type is not supported: {}".format(e, sel_par._rl_par.StorageType), title="Error")
            pass

    def GetName(self):
        return "Create Filters"


class CreateLegend(UI.IExternalEventHandler):
    def __init__(self):
        pass

    def Execute(self, uiapp):
        try:
            new_doc = revit.DOCS.doc
            # Get legend view
            collector = (
                DB.FilteredElementCollector(new_doc).OfClass(DB.View).ToElements()
            )

            legends = []
            for vw in collector:
                if vw.ViewType == DB.ViewType.Legend:
                    legends.append(vw)
                    break
            if len(legends) > 0:
                # Duplicate existing legend
                with revit.TransactionGroup(doc=new_doc, name="Create Legend"):
                    with revit.Transaction(doc=new_doc, name="Duplicate Legend"):
                        sel_cat = wndw._categories.SelectedItem["Value"]
                        sel_par = wndw._list_box1.SelectedItem["Value"]
                        new_id_legend = legends[0].Duplicate(
                            DB.ViewDuplicateOption.Duplicate
                        )
                        new_legend = new_doc.GetElement(new_id_legend)
                        i = 1
                        new_legend_name = (
                            str(
                                "Color Legend {} for View {}".format(
                                    (sel_cat._name + " / " + sel_par._name),
                                    revit.DOCS.doc.ActiveView.Name,
                                )
                            )
                            .replace("{", "")
                            .replace("}", "")
                        )
                        while True:
                            try:
                                new_legend.Name = str(new_legend_name + " - " + str(i))
                                break
                            except Exception:
                                i += 1
                                if i == 100:
                                    break
                    with revit.Transaction(doc=new_doc, name="Create Legend Graphic"):
                        ele_id_type = (
                            DB.FilteredElementCollector(new_doc)
                            .OfClass(DB.TextNoteType)
                            .FirstElementId()
                        )
                        list_max_X = []
                        list_y = []
                        # FilledRegionType
                        filled_type = []
                        all_types = (
                            DB.FilteredElementCollector(new_doc)
                            .OfClass(DB.FilledRegionType)
                            .ToElements()
                        )
                        for type in all_types:
                            pattern = new_doc.GetElement(type.ForegroundPatternId)
                            if pattern is not None:
                                if pattern.GetFillPattern().IsSolidFill:
                                    if type.ForegroundPatternColor.IsValid:
                                        filled_type.append(type)
                                        break
                        # Create Type if none is fill
                        if len(filled_type) == 0 and len(all_types) > 0:
                            it = 1
                            # Duplicate existing fillregiontype
                            while True:
                                try:
                                    new_type = all_types[0].Duplicate(
                                        "Fill Region " + str(it)
                                    )
                                    break
                                except:
                                    it += 1
                                    if it == 100:
                                        break
                            # Create pattern
                            it = 1
                            while True:
                                try:
                                    new_pattern = DB.FillPattern(
                                        "Fill Pattern " + str(it),
                                        DB.FillPatternTarget.Drafting,
                                        DB.FillPatternHostOrientation.ToView,
                                        float(0),
                                        float(0.00001),
                                    )
                                    new_elePat = DB.FillPatternElement.Create(
                                        new_doc, new_pattern
                                    )
                                    break
                                except:
                                    it += 1
                                    if it == 100:
                                        break
                            # Assign to type
                            new_type.ForegroundPatternId = new_elePat.Id
                            filled_type.append(new_type)
                        # Create Title
                        title_loc = DB.XYZ(0, 0, 0)
                        title_text = sel_cat._name + " / " + sel_par._name
                        legend_title = DB.TextNote.Create(
                            new_doc, new_legend.Id, title_loc, title_text, ele_id_type
                        )
                        new_doc.Regenerate()
                        title_bbox = legend_title.get_BoundingBox(new_legend)
                        offset = (title_bbox.Max.Y + title_bbox.Min.Y) * 2
                        # Create Text
                        for vw_item in wndw._list_box2.Items:
                            point = DB.XYZ(0, offset, 0)
                            index = wndw._list_box2.Items.IndexOf(vw_item)
                            if index != 0:
                                point = DB.XYZ(0, fin_coord_y, 0)
                            item = vw_item["Value"]
                            text_line = item._value
                            new_text = DB.TextNote.Create(
                                new_doc, new_legend.Id, point, text_line, ele_id_type
                            )
                            new_doc.Regenerate()
                            prev_bbox = new_text.get_BoundingBox(new_legend)
                            offset = (prev_bbox.Max.Y - prev_bbox.Min.Y) * 0.25
                            fin_coord_y = prev_bbox.Min.Y - offset
                            list_max_X.append(prev_bbox.Max.X)
                            list_y.append(fin_coord_y + offset)
                            height = (prev_bbox.Max.Y - prev_bbox.Min.Y) * 0.8
                        ini_x = max(list_max_X)
                        ogs = DB.OverrideGraphicSettings()
                        # Create filled color region
                        for indx, elem in enumerate(list_y):
                            coord_y = elem
                            item = wndw._list_box2.Items[indx]["Value"]
                            point0 = DB.XYZ(ini_x, coord_y, 0)
                            point1 = DB.XYZ(ini_x, coord_y + height, 0)
                            point2 = DB.XYZ(ini_x * 2, coord_y + height, 0)
                            point3 = DB.XYZ(ini_x * 2, coord_y, 0)
                            line01 = DB.Line.CreateBound(point0, point1)
                            line12 = DB.Line.CreateBound(point1, point2)
                            line23 = DB.Line.CreateBound(point2, point3)
                            line30 = DB.Line.CreateBound(point3, point0)
                            list_curveLoops = List[DB.CurveLoop]()
                            curveLoops = DB.CurveLoop()
                            curveLoops.Append(line01)
                            curveLoops.Append(line12)
                            curveLoops.Append(line23)
                            curveLoops.Append(line30)
                            list_curveLoops.Add(curveLoops)
                            reg = DB.FilledRegion.Create(
                                new_doc,
                                filled_type[0].Id,
                                new_legend.Id,
                                list_curveLoops,
                            )
                            # Assign color filled region
                            color = DB.Color(item._n1, item._n2, item._n3)
                            # ogs.SetProjectionLineColor(color)
                            ogs.SetSurfaceForegroundPatternColor(color)
                            ogs.SetCutForegroundPatternColor(color)
                            # ogs.SetProjectionLinePatternId(DB.ElementId(-1))
                            new_legend.SetElementOverrides(reg.Id, ogs)
            else:
                task2 = UI.TaskDialog("Color Elements by Parameter Value")
                task2.MainInstruction = "In order to create a new legend, you need to have at least one. Please, create a legend view."
                wndw.TopMost = False
                task2.Show()
                wndw.TopMost = True
        except Exception:
            pass

    def GetName(self):
        return "Create Legend"


class ValuesInfo:
    def __init__(self, para, val, id, n1, n2, n3):
        self._par = para
        self._value = val
        self._name = para.Definition.Name
        self._eleId = List[DB.ElementId]()
        self._eleId.Add(id)
        self._n1 = n1
        self._n2 = n2
        self._n3 = n3
        self._colour = Color.FromArgb(self._n1, self._n2, self._n3)


class ParaInfo:
    def __init__(self, type, para):
        self._type = type
        self._rl_par = para
        self._par = para.Definition
        self._name = para.Definition.Name


class CategInfo:
    def __init__(self, cat, param):
        self._name = cat.Name
        self._cat = cat
        self._intId = cat.Id.IntegerValue
        self._par = param


def get_active_view(ac_doc):
    sel_view = ac_doc.ActiveView
    if (
        sel_view.ViewType == DB.ViewType.ProjectBrowser
        or sel_view.ViewType == DB.ViewType.SystemBrowser
    ):
        sel_view = ac_doc.GetElement(uidoc.GetOpenUIViews()[0].ViewId)
    if not sel_view.CanUseTemporaryVisibilityModes():
        task2 = UI.TaskDialog("Color Elements by Parameter Value")
        task2.MainInstruction = (
            "Visibility settings cannot be modified in "
            + str(sel_view.ViewType)
            + " views. Please, change your current view."
        )
        try:
            wndw.TopMost = False
        except:
            pass
        task2.Show()
        try:
            wndw.TopMost = True
        except:
            pass
        return 0
    else:
        return sel_view


def get_value_par(para):
    value = ""
    if para.StorageType == DB.StorageType.Double:
        value = para.AsValueString()
    elif para.StorageType == DB.StorageType.ElementId:
        id_val = para.AsElementId()
        if id_val.IntegerValue >= 0:
            value = DB.Element.Name.__get__(doc.GetElement(id_val))
        else:
            value = "None"
    elif para.StorageType == DB.StorageType.Integer:
        if version > 2021:
            type = para.Definition.GetDataType()
            if DB.SpecTypeId.Boolean.YesNo == type:
                if para.AsInteger() == 1:
                    value = "True"
                else:
                    value = "False"
            else:
                value = para.AsValueString()
        else:
            type = para.Definition.ParameterType
            if DB.ParameterType.YesNo == type:
                if para.AsInteger() == 1:
                    value = "True"
                else:
                    value = "False"
            else:
                value = para.AsValueString()
    elif para.StorageType == DB.StorageType.String:
        value = para.AsString()
    else:
        value = "N/A"
    return value


def strip_accents(text):
    return "".join(char for char in normalize("NFKD", text) if category(char) != "Mn")


def random_color():
    r = randint(0, 230)
    g = randint(0, 230)
    b = randint(0, 230)
    return r, g, b


def get_range_of_values(category, param, new_view):
    for sample_bic in Enum.GetValues(DB.BuiltInCategory):
        if category._intId == int(sample_bic):
            bic = sample_bic
            break
    collector = (
        DB.FilteredElementCollector(doc, new_view.Id)
        .OfCategory(bic)
        .WhereElementIsNotElementType()
        .WhereElementIsViewIndependent()
        .ToElements()
    )
    list_values = []
    # Iterar todos los elementos y conseguir valores unicos
    for ele in collector:
        ele_par = ele
        if param._type == 1:
            ele_par = doc.GetElement(ele.GetTypeId())
        for pr in ele_par.Parameters:
            if pr.Definition.Name == param._par.Name:
                value = get_value_par(pr)
                if value == "" or value is None:
                    value = "N/A"
                match = [x for x in list_values if x._value == value]
                if len(match) > 0:
                    match[0]._eleId.Add(ele.Id)
                else:
                    while True:
                        r, g, b = random_color()
                        match = [
                            x
                            for x in list_values
                            if x._n1 == r and x._n2 == g and x._n3 == b
                        ]
                        if len(match) == 0:
                            val = ValuesInfo(pr, value, ele.Id, r, g, b)
                            list_values.append(val)
                            break
                break
    copy = [x for x in list_values if x._value == "N/A"]
    if len(copy) > 0:
        list_values.remove(copy[0])
    # Ordenar
    list_values.sort(key=lambda x: x._value, reverse=False)
    if len(list_values) > 1:
        try:
            first_value = list_values[0]._value
            indx_del = get_index_units(first_value)
            if indx_del == 0:
                list_values = sorted(list_values, key=lambda x: float(x._value))
            elif indx_del < len(first_value) and indx_del != -1:
                list_values = sorted(
                    list_values, key=lambda x: float(x._value[:-indx_del])
                )
        except Exception:
            pass
    if len(copy) > 0 and len(copy[0]._eleId) > 0:
        list_values.append(copy[0])
    return list_values


def get_used_categories_and_parameters(cat_exc, acti_view):
    # Get All elements and filter unneeded
    collector = (
        DB.FilteredElementCollector(doc, acti_view.Id)
        .WhereElementIsNotElementType()
        .WhereElementIsViewIndependent()
        .ToElements()
    )

    list_cat = []
    for ele in collector:
        if ele.Category is not None:
            current_int_cat_id = ele.Category.Id.IntegerValue
            if current_int_cat_id not in cat_exc:
                if not any(x._intId == current_int_cat_id for x in list_cat):
                    list_parameters = []
                    # Instance parameters
                    for par in ele.Parameters:
                        if (
                            par.Definition.BuiltInParameter
                            != DB.BuiltInParameter.ELEM_CATEGORY_PARAM
                            and par.Definition.BuiltInParameter
                            != DB.BuiltInParameter.ELEM_CATEGORY_PARAM_MT
                        ):
                            list_parameters.append(ParaInfo(0, par))
                    typ = ele.Document.GetElement(ele.GetTypeId())
                    # Type parameters
                    if typ is not None:
                        for par in typ.Parameters:
                            if (
                                par.Definition.BuiltInParameter
                                is not DB.BuiltInParameter.ELEM_CATEGORY_PARAM
                                and par.Definition.BuiltInParameter
                                is not DB.BuiltInParameter.ELEM_CATEGORY_PARAM_MT
                            ):
                                list_parameters.append(ParaInfo(1, par))
                    # Sort and add
                    list_parameters.sort(key=lambda x: x._name.upper(), reverse=False)
                    list_cat.append(CategInfo(ele.Category, list_parameters))
    list_cat.sort(key=lambda x: x._name, reverse=False)
    return list_cat


class FormCats(Form):
    def __init__(
        self, categories, ext_ev, uns_ev, s_view, reset_event, ev_legend, ev_filter
    ):
        self.IsOpen = 1
        self.legend_ev = ev_legend
        self.filter_ev = ev_filter
        self.reset_ev = reset_event
        self.crt_view = s_view
        self.event = ext_ev
        self.uns_event = uns_ev
        self.uns_event.Raise()
        self.categs = categories
        self.width_par = 1
        self._categories_table_data = DataTable("Data")
        self._categories_table_data.Columns.Add("Key", String)
        self._categories_table_data.Columns.Add("Value", Object)
        names = [x._name for x in self.categs]
        self._categories_table_data.Rows.Add("Select a Category Here!", 0)
        [
            self._categories_table_data.Rows.Add(key_, value_)
            for key_, value_ in zip(names, self.categs)
        ]
        self.out = []
        self.InitializeComponent()

    def InitializeComponent(self):
        self._categories = ComboBox()
        self._list_box1 = CheckedListBox()
        self._list_box2 = ListBox()
        self._button1 = Button()
        self._button2 = Button()
        self._button3 = Button()
        self._button4 = Button()
        self._button5 = Button()
        self._button6 = Button()
        self._txt_block2 = Label()
        self._txt_block3 = Label()
        self._txt_block4 = Label()
        self._txt_block5 = Label()
        self.SuspendLayout()
        #
        # TextBlock2
        #
        self._txt_block2.Anchor = (
            AnchorStyles.Bottom
            | AnchorStyles.Left
        )
        self._txt_block2.Location = Point(12, 10)
        self._txt_block2.Name = "txtBlock2"
        self._txt_block2.Size = Size(120, 20)
        self._txt_block2.Text = "Category:"
        #
        # comboBox1 Cat
        #
        self._categories.Anchor = (
            AnchorStyles.Top
            | AnchorStyles.Bottom
            | AnchorStyles.Left
            | AnchorStyles.Right
        )
        self._categories.Location = Point(12, 27)
        self._categories.Name = "dropDown"
        self._categories.DataSource = self._categories_table_data
        self._categories.DisplayMember = "Key"
        self._categories.Size = Size(310, 244)
        self._categories.DropDownWidth = 150
        self._categories.DropDownStyle = ComboBoxStyle.DropDownList
        self._categories.SelectedIndexChanged += self.update_filter
        #
        # TextBlock3
        #
        self._txt_block3.Anchor = (
            AnchorStyles.Bottom
            | AnchorStyles.Left
        )
        self._txt_block3.Location = Point(12, 53)
        self._txt_block3.Name = "txtBlock3"
        self._txt_block3.Size = Size(120, 13)
        self._txt_block3.Text = "Parameters:"
        #
        # checkedListBox1
        #
        self._list_box1.Anchor = (
            AnchorStyles.Top
            | AnchorStyles.Left
            | AnchorStyles.Bottom
            | AnchorStyles.Right
        )
        self._list_box1.FormattingEnabled = True
        self._list_box1.CheckOnClick = True
        self._list_box1.HorizontalScrollbar = True
        self._list_box1.Location = Point(12, 70)
        self._list_box1.Name = "checkedListBox1"
        self._list_box1.DisplayMember = "Key"
        self._list_box1.Size = Size(310, 170)
        self._list_box1.ItemCheck += self.check_item
        #
        # TextBlock4
        #
        self._txt_block4.Anchor = (
            AnchorStyles.Bottom
            | AnchorStyles.Left
        )
        self._txt_block4.Location = Point(12, 245)
        self._txt_block4.Name = "txtBlock4"
        self._txt_block4.Size = Size(120, 13)
        self._txt_block4.Text = "Values:"
        #
        # TextBlock5
        #
        self._txt_block5.Anchor = (
            AnchorStyles.Bottom
            | AnchorStyles.Left
        )
        self._txt_block5.Location = Point(12, 557)
        self._txt_block5.Name = "txtBlock5"
        self._txt_block5.Size = Size(310, 27)
        self._txt_block5.Text = (
            "*Spaces may require you to apply a color scheme in the view."
        )
        self._txt_block5.ForeColor = Color.Red
        self._txt_block5.Font = Font("Arial", 8, FontStyle.Underline)
        self._txt_block5.Visible = False
        #
        # checkedListBox2
        #
        self._list_box2.Anchor = (
            AnchorStyles.Top
            | AnchorStyles.Left
            | AnchorStyles.Bottom
            | AnchorStyles.Right
        )
        self._list_box2.FormattingEnabled = True
        self._list_box2.HorizontalScrollbar = True
        self._list_box2.Location = Point(12, 262)
        self._list_box2.Name = "listBox2"
        self._list_box2.DisplayMember = "Key"
        self._list_box2.Size = Size(310, 280)
        self._list_box2.DrawMode = DrawMode.OwnerDrawFixed
        self._list_box2.DrawItem += self.colour_item
        #
        # button1
        #
        self._button1.Anchor = (
            AnchorStyles.Bottom
            | AnchorStyles.Right
        )
        self._button1.Location = Point(222, 592)
        self._button1.Name = "button1"
        self._button1.Size = Size(100, 27)
        self._button1.Text = "Apply Colors"
        self._button1.UseVisualStyleBackColor = True
        self._button1.Click += self.button_1_click
        #
        # button2
        #
        self._button2.Anchor = (
            AnchorStyles.Bottom
            | AnchorStyles.Right
        )
        self._button2.Location = Point(12, 592)
        self._button2.Name = "button2"
        self._button2.Size = Size(100, 27)
        self._button2.Text = "Reset All Colors"
        self._button2.UseVisualStyleBackColor = True
        self._button2.Click += self.button_2_click
        #
        # button3
        #
        self._button3.Anchor = (
            AnchorStyles.Bottom
            | AnchorStyles.Right
        )
        self._button3.Location = Point(11, 538)
        self._button3.Name = "button3"
        self._button3.Size = Size(156, 20)
        self._button3.Text = "Random Colors"
        self._button3.UseVisualStyleBackColor = True
        self._button3.Click += self.button_3_click
        #
        # button4
        #
        self._button4.Anchor = (
            AnchorStyles.Bottom
            | AnchorStyles.Right
        )
        self._button4.Location = Point(167, 538)
        self._button4.Name = "button4"
        self._button4.Size = Size(156, 20)
        self._button4.Text = "Gradient Colors"
        self._button4.UseVisualStyleBackColor = True
        self._button4.Click += self.button_4_click
        #
        # button5
        #
        self._button5.Anchor = (
            AnchorStyles.Bottom
            | AnchorStyles.Right
        )
        self._button5.Location = Point(11, 558)
        self._button5.Name = "button5"
        self._button5.Size = Size(156, 20)
        self._button5.Text = "Create a Legend"
        self._button5.UseVisualStyleBackColor = True
        self._button5.Click += self.button_5_click
        #
        # button6
        #
        self._button6.Anchor = (
            AnchorStyles.Bottom
            | AnchorStyles.Right
        )
        self._button6.Location = Point(167, 558)
        self._button6.Name = "button6"
        self._button6.Size = Size(156, 20)
        self._button6.Text = "Create View Filters"
        self._button6.UseVisualStyleBackColor = True
        self._button6.Click += self.button_6_click
        #
        # Form
        #
        self.TopMost = True
        self.ShowInTaskbar = False
        self.ClientSize = Size(334, 630)
        self.MaximizeBox = 0
        self.MinimizeBox = 0
        self.CenterToScreen()
        self.FormBorderStyle = FormBorderStyle.FixedSingle
        self.Controls.Add(self._button1)
        self.Controls.Add(self._button2)
        self.Controls.Add(self._button3)
        self.Controls.Add(self._button4)
        self.Controls.Add(self._button5)
        self.Controls.Add(self._button6)
        self.Controls.Add(self._categories)
        self.Controls.Add(self._txt_block2)
        self.Controls.Add(self._txt_block3)
        self.Controls.Add(self._txt_block4)
        self.Controls.Add(self._txt_block5)
        self.Controls.Add(self._list_box1)
        self.Controls.Add(self._list_box2)
        self.Name = "Color Elements By Parameter Value"
        self.Text = "Color Elements By Parameter Value"
        script.get_script_path()
        icon_filename = script.get_script_path() + ".\\icon.ico"
        if not os.path.exists(icon_filename):
            icon_filename = script.get_script_path() + ".\\icon.ico"
        icon = Icon(icon_filename)
        self.Icon = icon
        self.Closing += self.closing_event
        self.ResumeLayout(False)

    def button_1_click(self, sender, e):
        if self._list_box2.Items.Count > 0:
            self.event.Raise()

    def button_2_click(self, sender, e):
        self.reset_ev.Raise()

    def button_3_click(self, sender, e):
        # Reassign Random colors
        try:
            checkindex = self._list_box1.CheckedIndices
            for indx in checkindex:
                self._list_box1.SetItemChecked(indx, False)
                self._list_box1.SetItemChecked(indx, True)
        except:
            pass

    def button_4_click(self, sender, e):
        self._list_box2.SelectedIndexChanged -= self.list_selected_index_changed
        try:
            list_values = []
            number_items = len(self._list_box2.Items)
            if number_items > 2:
                st_color = self._list_box2.Items[0]["Value"]._colour
                end_color = self._list_box2.Items[number_items - 1]["Value"]._colour
                list_colors = self.get_gradient_colors(st_color, end_color, number_items)
                for indx in range(len(self._list_box2.Items)):
                    item = self._list_box2.Items[indx]["Value"]
                    item._n1 = abs(list_colors[indx][1])
                    item._n2 = abs(list_colors[indx][2])
                    item._n3 = abs(list_colors[indx][3])
                    item._colour = Color.FromArgb(item._n1, item._n2, item._n3)
                    list_values.append(item)
                self._table_data3 = DataTable("Data")
                self._table_data3.Columns.Add("Key", String)
                self._table_data3.Columns.Add("Value", Object)
                vl_par = [x._value for x in list_values]
                [
                    self._table_data3.Rows.Add(key_, value_)
                    for key_, value_ in zip(vl_par, list_values)
                ]
                self._list_box2.DataSource = self._table_data3
                self._list_box2.DisplayMember = "Key"
                self._list_box2.SelectedIndex = -1
        except Exception:
            pass
        self._list_box2.SelectedIndexChanged += self.list_selected_index_changed

    def button_5_click(self, sender, e):
        if self._list_box2.Items.Count > 0:
            self.legend_ev.Raise()

    def button_6_click(self, sender, e):
        if self._list_box2.Items.Count > 0:
            self.filter_ev.Raise()

    def get_gradient_colors(self, start_color, end_color, steps):
        aStep = float((end_color.A - start_color.A) / steps)
        rStep = float((end_color.R - start_color.R) / steps)
        gStep = float((end_color.G - start_color.G) / steps)
        bStep = float((end_color.B - start_color.B) / steps)
        colorList = []
        for index in range(steps):
            a = start_color.A + int(aStep * index) - 1
            r = start_color.R + int(rStep * index) - 1
            g = start_color.G + int(gStep * index) - 1
            b = start_color.B + int(bStep * index) - 1
            if a < 0:
                a = 0
            if r < 0:
                r = 0
            if g < 0:
                g = 0
            if b < 0:
                b = 0
            colorList.append([a, r, g, b])
        return colorList

    def closing_event(self, sender, e):
        self.IsOpen = 0
        self.uns_event.Raise()

    def list_selected_index_changed(self, sender, e):
        # Ask colour
        if sender.SelectedIndex != -1:
            clr_dlg = ColorDialog()
            clr_dlg.AllowFullOpen = True
            if clr_dlg.ShowDialog() == DialogResult.OK:
                sender.SelectedItem["Value"]._n1 = clr_dlg.Color.R
                sender.SelectedItem["Value"]._n2 = clr_dlg.Color.G
                sender.SelectedItem["Value"]._n3 = clr_dlg.Color.B
                sender.SelectedItem["Value"]._colour = Color.FromArgb(
                    clr_dlg.Color.R, clr_dlg.Color.G, clr_dlg.Color.B
                )
            self._list_box2.SelectedIndex = -1

    def colour_item(self, sender, e):
        cnt = e.Index
        g = e.Graphics
        text_device = sender.Items[e.Index]["Key"]
        if cnt == self._list_box2.SelectedIndex:
            color = Color.White
            font_color = Color.Black
        else:
            color = sender.Items[e.Index]["Value"]._colour
            font_color = Color.White
        e.DrawBackground()
        g.FillRectangle(SolidBrush(color), e.Bounds)
        TextRenderer.DrawText(
            g, text_device, Font("Arial", 9, FontStyle.Bold), e.Bounds, font_color
        )
        e.DrawFocusRectangle()

    def check_item(self, sender, e):
        # Only one element can be selected
        for indx in range(self._list_box1.Items.Count):
            if indx != e.Index:
                self._list_box1.SetItemChecked(indx, False)
        try:
            self._list_box2.SelectedIndexChanged -= self.list_selected_index_changed
        except:
            pass
        sel_cat = self._categories.SelectedItem["Value"]
        sel_param = sender.Items[e.Index]["Value"]
        if sel_cat is not None and sel_cat != 0:
            self._table_data3 = DataTable("Data")
            self._table_data3.Columns.Add("Key", String)
            self._table_data3.Columns.Add("Value", Object)
            if e.NewValue == CheckState.Unchecked:
                self._list_box2.DataSource = self._table_data3
                self._list_box2.DisplayMember = "Key"
            else:
                rng_val = get_range_of_values(sel_cat, sel_param, self.crt_view)
                vl_par = [x._value for x in rng_val]
                g = self._list_box2.CreateGraphics()
                width = [
                    int(g.MeasureString(x, self._list_box2.Font).Width) for x in vl_par
                ]
                self._list_box2.HorizontalExtent = max(width) + 50
                [
                    self._table_data3.Rows.Add(key_, value_)
                    for key_, value_ in zip(vl_par, rng_val)
                ]
                self._list_box2.DataSource = self._table_data3
                self._list_box2.DisplayMember = "Key"
                self._list_box2.SelectedIndex = -1
                self._list_box2.SelectedIndexChanged += self.list_selected_index_changed

    def update_filter(self, sender, e):
        # Update param listbox
        sel_cat = sender.SelectedItem["Value"]
        self._table_data2 = DataTable("Data")
        self._table_data2.Columns.Add("Key", String)
        self._table_data2.Columns.Add("Value", Object)
        self._table_data3 = DataTable("Data")
        self._table_data3.Columns.Add("Key", String)
        self._table_data3.Columns.Add("Value", Object)
        if sel_cat != 0 and sender.SelectedIndex != 0:
            names_par = [x._name for x in sel_cat._par]
            [
                self._table_data2.Rows.Add(key_, value_)
                for key_, value_ in zip(names_par, sel_cat._par)
            ]
            self._list_box1.DataSource = self._table_data2
            self._list_box1.DisplayMember = "Key"
            for indx in range(self._list_box1.Items.Count):
                self._list_box1.SetItemChecked(indx, False)
            self._list_box2.DataSource = self._table_data3
        else:
            self._list_box1.DataSource = self._table_data2
            self._list_box2.DataSource = self._table_data3


def get_index_units(str_value):
    for let in str_value[::-1]:
        if let.isdigit():
            return str_value[::-1].index(let)
    return -1


doc = revit.DOCS.doc
uidoc = HOST_APP.uiapp.ActiveUIDocument
app = HOST_APP.app
version = int(app.VersionNumber)
uiapp = HOST_APP.uiapp

sel_view = get_active_view(doc)
if sel_view != 0:
    # Categories to exclude
    cat_excluded = [
        int(DB.BuiltInCategory.OST_RoomSeparationLines),
        int(DB.BuiltInCategory.OST_Cameras),
        int(DB.BuiltInCategory.OST_CurtainGrids),
        int(DB.BuiltInCategory.OST_Elev),
        int(DB.BuiltInCategory.OST_Grids),
        int(DB.BuiltInCategory.OST_IOSModelGroups),
        int(DB.BuiltInCategory.OST_Views),
        int(DB.BuiltInCategory.OST_SitePropertyLineSegment),
        int(DB.BuiltInCategory.OST_SectionBox),
        int(DB.BuiltInCategory.OST_ShaftOpening),
        int(DB.BuiltInCategory.OST_BeamAnalytical),
        int(DB.BuiltInCategory.OST_StructuralFramingOpening),
        int(DB.BuiltInCategory.OST_MEPSpaceSeparationLines),
        int(DB.BuiltInCategory.OST_DuctSystem),
        int(DB.BuiltInCategory.OST_Lines),
        int(DB.BuiltInCategory.OST_PipingSystem),
        int(DB.BuiltInCategory.OST_Matchline),
        int(DB.BuiltInCategory.OST_CenterLines),
        int(DB.BuiltInCategory.OST_CurtainGridsRoof),
        int(DB.BuiltInCategory.OST_SWallRectOpening),
        -2000278,
    ]
    # Get categories in used
    categ_inf_used = get_used_categories_and_parameters(cat_excluded, sel_view)
    if len(categ_inf_used) == 0:
        alert('No categories found in the current view. Please, change your current view.')
        script.exit()
    # Window
    event_handler = ApplyColors()
    ext_event = UI.ExternalEvent.Create(event_handler)

    event_handler_uns = SubscribeView()
    ext_event_uns = UI.ExternalEvent.Create(event_handler_uns)

    event_handler_reset = ResetColors()
    ext_event_reset = UI.ExternalEvent.Create(event_handler_reset)

    event_handler_Legend = CreateLegend()
    ext_event_legend = UI.ExternalEvent.Create(event_handler_Legend)

    event_handler_filters = CreateFilters()
    ext_event_filters = UI.ExternalEvent.Create(event_handler_filters)

    wndw = FormCats(
        categ_inf_used,
        ext_event,
        ext_event_uns,
        sel_view,
        ext_event_reset,
        ext_event_legend,
        ext_event_filters,
    )
    wndw._categories.SelectedIndex = -1
    wndw.Show()
